### ISSUE TITLE
Draw maps from MIZ

### ISSUE THREAD

**Issue by etcher-be** [etcher-be/EMFT_ARCHIVE#20]
Generate KML & JSON from hidden units polygons

WIP derp: https://github.com/132nd-etcher/EMFT/commit/719aacb6d89d4e3bae070811f6319d83f01af563

Libs:

* https://folium.readthedocs.io/en/latest/
* https://pypi.python.org/pypi/geojson

**Comment by 132nd-etcher** [comment]
Add option to export initial points from the mission DB.
